name: Deploy to Github Pages ğŸš€

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 02.Area/è®°å½•/åšå®¢/hugo-pages/**
        
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: 02.Area/è®°å½•/åšå®¢/hugo-pages
    permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
      contents: write

    steps:
      - name: Set Timezone ğŸŒï¸
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache Hugo resources ğŸ—ƒï¸
        uses: actions/cache@v4
        env:
          cache-name: cache-hugo-resources
        with:
          path: resources
          key: ${{ env.cache-name }}

      - name: Setup Go ğŸ› ï¸
        uses: actions/setup-go@v5
        with:
          go-version: "^1.17.0"
      - run: go version

      - name: Setup Hugo âš™ï¸
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build ğŸ”§
        run: hugo --minify --gc --destination ./public
        working-directory: 02.Area/è®°å½•/åšå®¢/hugo-pages

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: 02.Area/è®°å½•/åšå®¢/hugo-pages/public
          clean: true
          single-commit: true
          token: ${{ secrets.action }}
          repository-name: i-lovet/i-lovet.github.io
